version: '3'

services:
  frontend:
    image: abizhov/shop-chebureks-frontend
    restart: always
    ports:
      - 3333:3000
    
  backend:
    image: abizhov/shop-chebureks-backend
    restart: always
    ports:
      - 5555:5000
    depends_on:
      - mongodb
    env_file:
      - ./back/.env
  mongodb:
    image: mongo
    volumes:
      - mongodata_pub:/data/db
    restart: unless-stopped
    ports:
      - 27017:27017
    environment:
      DATABASE_USER: test
      DATABASE_PASSWORD: test

volumes:
  mongodata_pub: